### PR TITLE
Update to support multi-plug devices (HS300).

### PR DESCRIPTION
**Pull request by MaddyTP**
* Update smart-plug.js to support multi-plug.

* Update README.md with multi-plug example.

### CODE REVIEW

**Comment by MaddyTP** [comment]
Support for multi-plug devices required a major rewrite of smart-plug.js.  

Tested and working on HS300.


2020-05-21 09_22_44-Window

**Comment by caseyjhol** [comment]
Was going to merge this as part of the next release - any reason you closed it?

**Comment by MaddyTP** [comment]
Closed it to work through an issue where the child devices were being inserted into the device array out of order, causing the wrong plug to come on when sending payload.  There was also a short delay in returning the child devices which was erroring if a payload was sent to the node too quickly after startup/deploy.  

Will also need the code tested on a single plug device to verify it works properly, all I have is a HS300 for testing.

**Comment by caseyjhol** [comment]
I see. Thanks for your work on this. I only have access to the smart switches right now, so we'll need somebody else to test too.

**Comment by MaddyTP** [comment]
Glad to be of help!  I'll have a new PR up from a fresh fork once the issues are worked out, hopefully by end of next weekend.

**Comment by MaddyTP** [comment]
New PR is up.

**Pull request closed without merging**
