### PR TITLE
Make error catchable

### PR DESCRIPTION
**Pull request by JsBergbau**
Make error "not reachable" catchable, so you can catch it with a catchnode and react to it

### CODE REVIEW

**Comment by caseyjhol** [comment]
Looks like the error is already catchable (possibly due to #7). Implementing this PR throws some errors in the Node-RED log.

**Comment by JsBergbau** [comment]
> 
> 
> Looks like the error is already catchable (possibly due to #7). Implementing this PR throws some errors in the Node-RED log.

Did you test the latest commit with this changed code? 
```
            if (error) node.error(error);
```
replaced by:
```
            var msg = (typeof msg === 'undefined') ? {"_msgid":"704568d5.b1c768","topic":node.deviceInstance.mac,"payload":"Probably error cause: time is not sync"} : msg;
            //node.warn(device.ip);
            if (error) node.error(error,msg);
```

In the first commit indeed there were some errors thrown. I'm using this version for about one week and everything works fine so far. If so can you please post some log entries you refer to?

In https://github.com/caseyjhol/node-red-contrib-tplink/pull/7 there is still   `if (error) node.error(error);` 

However to have it catchable you need to call it with a msg object as second argument 
`node.error("hit an error", msg);`
https://nodered.org/docs/user-guide/writing-functions#handling-errors

**Comment by caseyjhol** [comment]
I see the issue now - will c7cf509a2c916f44c1483e922d5a678ccd09c75f work for you?

**Comment by JsBergbau** [comment]
Thanks for fixing that. The code itself looks good. However you changed so much, 0.3.0 version doesn't work at all for me anymore. First, it seems there is no status outputtet anymore. I had this flow
grafik
As you can see: You see an overview at once. Which devices are on or off and their power consumption. Could you implement this status again? It was very useful. Positive to say: Even with time not set I could turn the device on and off without any error anymore.

The inject node I use is
```
[{"id":"ad1d57d3.fb8888","type":"inject","z":"e2a29bb2.0ee9f","name":"Startinitialisierung","topic":"","payload":"getInfoEvents|getMeterEvents","payloadType":"str","repeat":"10","crontab":"","once":true,"onceDelay":"5","x":590,"y":580,"wires":[["2dff4d27.daa9d2","7e5224f7.29a4bc","75278c24.ed8f34","4b83b030.e60bf8","f1b9fa.0dfe5608"]]}]
```
So if added to Event subscriptions via pipe "|" sign. This seems not to be possible anymore. Personally I find it a bad idea to change code in that way that it breaks with existing flows. Consider all the users using your node in an flow and not working anymore.

I tried using with this code
```
[{"id":"7e2d4816.008058","type":"inject","z":"1ce15e53.bf3222","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":530,"y":440,"wires":[["68fcedc3.371a24"]]},{"id":"f781eab4.336388","type":"inject","z":"1ce15e53.bf3222","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":550,"y":520,"wires":[["68fcedc3.371a24"]]},{"id":"68fcedc3.371a24","type":"smart-plug","z":"1ce15e53.bf3222","name":"TPlink - HS110(EU)","device":"192.168.178.32","interval":10000,"eventInterval":1000,"x":790,"y":400,"wires":[["2108d36.6d57f2c"]]},{"id":"2108d36.6d57f2c","type":"debug","z":"1ce15e53.bf3222","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1130,"y":340,"wires":[]},{"id":"a12e2aa7.295ea8","type":"change","z":"1ce15e53.bf3222","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"events\":[\"getMeterUpdateEvents\",\"getPowerEvents\"]}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":520,"y":340,"wires":[["68fcedc3.371a24"]]},{"id":"9ede087c.231ea8","type":"change","z":"1ce15e53.bf3222","name":"","rules":[{"t":"set","p":"events","pt":"msg","to":"[\"getMeterUpdateEvents\",\"getPowerEvents\"]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":280,"wires":[["68fcedc3.371a24"]]},{"id":"76940493.51df1c","type":"inject","z":"1ce15e53.bf3222","name":"","topic":"","payload":"getMeterInfo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":400,"wires":[["68fcedc3.371a24"]]},{"id":"4a12bea4.78a1","type":"inject","z":"1ce15e53.bf3222","name":"Startinitialisierung","topic":"","payload":"getInfoEvents|getMeterEvents","payloadType":"str","repeat":"10","crontab":"","once":true,"onceDelay":"5","x":230,"y":300,"wires":[["9ede087c.231ea8","a12e2aa7.295ea8"]]}]
```
I only get output of the debug node when clicking on the true/false or getMeterInfo node. But I don't get any automatically updates like in the poll intervall frequency. 
Whats wrong with my flow?

**Comment by MaddyTP** [comment]
PR #12 corrects issue with "|" sign to separate events.

**Comment by caseyjhol** [comment]
@JsBergbau I just released a new version that addresses some of your concerns. Please check to see if things are functioning normally again. If not, create a new issue to address anything not working.

**Comment by JsBergbau** [comment]
Hi caseyjhol. Sorry, but its now even worse. I've created a new issue https://github.com/caseyjhol/node-red-contrib-tplink/issues/15

**Comment by caseyjhol** [comment]
@JsBergbau I see where the issue stems from - `getInfoEvents` and `getMeterEvents` were removed in v0.3.0. I apologize for not catching that sooner.

**Comment by JsBergbau** [comment]
Do they conflict with supporting devices with multiple plugs? I don't think so, since its based upon https://github.com/plasticrake/tplink-smarthome-api 
Can you re-add them? As I said you shouldn't break with existing setups. At least the basic functionality should remain when users do an update.

**Comment by caseyjhol** [comment]
@JsBergbau Yes, we'll be re-adding them - their removal was not intentional.

**Pull request closed without merging**
