### PR TITLE
Move .deviceConnected=true into the promise

### PR DESCRIPTION
**Pull request by hufftheweevil**
This fix prevents an error from occurring if an action is called before the device connects.

### CODE REVIEW

**Comment by MaddyTP** [comment]
Not sure why, but this change does not work on multi-plug devices (HS107/HS300).

**Comment by hufftheweevil** [comment]
Odd - I haven't had time to test this out, but just looking at the code it doesn't seem like there should be an issue with the multi-plug path. Are you saying it never changes the `.deviceConnected` flag to true?

Also - I'm a little new to the whole PR business - I thought I could make a separate PR for a different commit to my fork, but now I realized it just added it to this one. The other commit just adds the device IP to the output messages as the `.topic` - helpful for when you connect multiple nodes up to one function.

**Comment by MaddyTP** [comment]
Yeah, I don’t see a problem including this in the promise either, but the flag never changes for HS107/HS300.  These just won’t connect with those two lines moved into the promise.

**Comment by caseyjhol** [comment]
@hufftheweevil In the future, you'll want to create a separate branch for a new feature, and that will allow you to submit multiple PRs and continue to make changes without one branch affecting the other.

**Comment by hufftheweevil** [comment]
Closing to create separate PRs for each change and debug issue with original PR

**Pull request closed without merging**
