### PR TITLE
Multi-Plug Support (HS300)

### PR DESCRIPTION
**Pull request by MaddyTP**
Adds multi-plug support.

### CODE REVIEW

**Comment by MaddyTP** [comment]
Confirmed working with HS300.  I've ordered a HS100, HS105, and HS107 for further verification.

**Comment by caseyjhol** [comment]
Awesome - thanks!

**Comment by caseyjhol** [comment]
Out of curiosity - what's your reasoning behind removing `getMeterUpdateEvents` and `getPowerEvents`?

**Comment by MaddyTP** [comment]
Both should still be in the code...

`node.sendEvent = function (event, device, value) {
            switch (event) {
                case 'power-on':
                case 'power-off':
                    if (node.checkAction('getPowerEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.state = value;
                        msg.payload.device = node.deviceInstance.findIndex(x => x === device);
                        msg.payload.timestamp = moment().format();
                        msg.payload.instances = node.childs;
                        node.send(msg);
                    };
                    break;
                case 'power-update':
                    if (node.checkAction('getPowerUpdateEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.state = value;
                        msg.payload.device = node.deviceInstance.findIndex(x => x === device);
                        msg.payload.timestamp = moment().format();
                        node.send(msg);
                    };
                    break;
                case 'in-use':
                case 'not-in-use':
                    if (node.checkAction('getInUseEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.state = value;
                        msg.payload.device = node.deviceInstance.findIndex(x => x === device);
                        msg.payload.timestamp = moment().format();
                        node.send(msg);
                    };
                    break;
                case 'in-use-update':
                    if (node.checkAction('getInUseUpdateEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.state = value;
                        msg.payload.device = node.deviceInstance.findIndex(x => x === device);
                        msg.payload.timestamp = moment().format();
                        node.send(msg);
                    };
                    break;
                case 'emeter-realtime-update':
                    if (node.checkAction('getMeterUpdateEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.emeter = value;
                        msg.payload.device = node.deviceInstance.findIndex(x => x === device);
                        msg.payload.timestamp = moment().format();
                        node.send(msg);
                    };
                    break;
                case 'device-online':
                case 'device-offline':
                    if (node.checkAction('getOnlineEvents')) {
                        let msg = {};
                        msg.payload = {};
                        msg.payload.event = event;
                        msg.payload.state = value;
                        msg.payload.device = device;
                        msg.payload.timestamp = moment().format();
                        node.send(msg);
                    };
                    if (event === 'device-offline') node.status({ fill: 'red', shape: 'ring', text: 'Offline' });
                    if (event === 'device-online') node.status({ fill: 'green', shape: 'dot', text: 'Online' });
                    break;
            }
}`

I did make some changes to the events to distinguish between the different type of events.  Separated getPowerEvents/getInUseEvents from getPowerUpdateEvents/getInUseUpdateEvents as one emits on change and the latter emits recurring per polling interval.  getMeterUpdateEvents was updated as it is a polling event so now includes the "Update" to distinguish  it.  

Hope this makes sense...

**Comment by MaddyTP** [comment]
Also just noticed I left a line of test code in this function...please remove the following line of code from master.

```
msg.payload.instances = node.childs;
```

**Comment by MaddyTP** [comment]
PR #9 submitted to improve event emit details and remove line of left test code.

**Comment by caseyjhol** [comment]
Not sure how I missed that. Thanks.

**Comment by caseyjhol** [comment]
I guess I just wrote the wrong event names - looks like `getMeterEvents` and `getInfoEvents` are the ones that are now gone. Should probably add those back in for backwards compatibility. I don't want to break anybody's config.

**Comment by MaddyTP** [comment]
I can add those back in today.

**Pull request merged**
