### PR TITLE
Multi-Plug Support - Patch4

### PR DESCRIPTION
**Pull request by MaddyTP**
Adds 'getInfoEvents' to support backwards compatibility.

### CODE REVIEW

**Comment by caseyjhol** [comment]
While getInfoEvents works again, it seems to be ignoring the event interval after the initial response.

**Comment by MaddyTP** [comment]
Hmm...it should be running off the 'getPowerUpdateEvents' interval which emits on polling interval.  Let me look into it...

**Comment by MaddyTP** [comment]
Confirmed working for HS100/HS105/HS107/HS300.  'getInfoEvents' and 'getMeterEvents' are the only obvious issues.

image

**Comment by caseyjhol** [comment]
Solved the event interval issue in v0.4.3.

**Pull request merged**
