### PR TITLE
Full Rework

### PR DESCRIPTION
**Pull request by hufftheweevil**
See https://github.com/caseyjhol/node-red-contrib-tplink/issues/23 for more info

### CODE REVIEW

**Comment by caseyjhol** [comment]
A small thing, but I wonder if we should change the name of the node to `kasa` instead of `tplink`? It seems TP-Link has removed their branding from the Kasa site: https://www.kasasmart.com. Open to suggestions of course.

**Comment by hufftheweevil** [comment]
I've got nothing against that

**Comment by caseyjhol** [comment]
Getting an error with my HS220 - `"TypeError: node.newDevice is not a function"`. `node.newDevice` isn't defined anywhere.

**Comment by hufftheweevil** [comment]
Whoops - I had done some last minute changes and forgot to do a full test. See PR https://github.com/caseyjhol/node-red-contrib-tplink/pull/26

**Pull request merged**
